version: '3.8'
services:
  fish-client:
    container_name: fish-client
    image: fish-client:latest
    build:
      context: ../fish-client
      dockerfile: ../fish-client/Dockerfile
    ports:
      - '3000:3000'
  fish-app:
    container_name: fish-app
    image: fish-app:latest
    build:
      context: ../fish-app
      dockerfile: ../fish-app/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local